# Programming for Data Analysis Assignment 2020

The purpose of this document is to perform a high level analysis of the Numpy.Random package. 

There will be multiple components to this analysis, as detailed below, viewed through a prism of practical data analysis as well as graphics created to illustrate this data best. 

The areas under review are as follow:

### **Explain the overall purpose of the package**
- Origin of the package and its intended audience

<br>

### Explain the use of the simple random data function. 
- Where does the Simple Random Data sit in this package and what does it facilitate

### Explain the use of Permutations Funcitons. 
- How do permutations allow for data to be viewed in different sequences


### Expain the use and purpose of at least five distributions functions. 
- Using data and being able to visualise for a wider audience beyonf raw data


### Explain the use of seeds in generations pseudorandom numbers.
- What is a seed and what does it enable

While there is an extensive amount of information available, and a large amount of research conducted in this area, the primary area of investigation will be conducted on the official Numpy Documentation catalogue listed [here](https://numpy.org/doc/stable/reference/random/index.html)

### Numpy.Random

Within it's hierarchail structure, the numpy package is divided into two core parts, *BitGenerators* and *Generators*. 
We will be at first reviewing the Bitgenerator, via some sample code to demonstrate the packages capabilities.<br>
<br>
The principle purpose of the package is random number generation, as per [Numpy.org](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#quick-start). Numpy, as per the latest edition of the package, has been updated to include several upgrades in the package. Principle among these, is the introduction of the Permuted Congruential Generator 64 as the default pseudo random number generator. Otherwise known as PCG64, it supports the methods for how random number generation operates [Numpy.Org](https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html\0)

### BitGenerator

As per the official documentation on the [numpy.org](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.html#numpy.random.BitGenerator) the bit generator performs a very limited number of tasks within the numpy.random pakage.

NEED TO EXPLAIN THE TWO STREAMS OF A BIITGENERATOR, HOW IT SUES STATE AN SEEDING. 

### Software Requirements

There are a number of pieces of software that are required in order to run this analysis. These are: 

- Numpy
- MatPlotLib
- Jupyter Notebook


In [1]:
import numpy as np

In [2]:
np.random.BitGenerator

numpy.random.bit_generator.BitGenerator

In [3]:
np.random.BitGenerator.random_raw()

TypeError: descriptor 'random_raw' of 'numpy.random.bit_generator.BitGenerator' object needs an argument

This is the source for a bitgenerator test.
Source [numpy.org](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.random_raw.html#numpy.random.BitGenerator.random_raw) 

In [4]:
from numpy.random import default_rng

In [ ]:
# what is it you're trying to prove here - give it a reason or get rid.

In [5]:
rg = default_rng(12)
rg.random()

0.2508244581084461

### Generator



Following on from the bitgenerator, we have the generator, which is actually a container for the Bitgenerator

THERE NEEDS TO BE A BUG AUL SPEECH IN HERE ON THE RANDOM.DEFAULT.RNG()

### Simple Random Data

We have seen from the structured nature of this package, that there are a  number of interdependencies in order for it to run successfully. Next, as part of our analysis into the package, we have the area of simple random data. 
There are four core sections to this section of the package. They are:  

- Integers
- Random
- Choice
- Bytes

Each section has it's own capabilities added to it to make it distinguishable from the last, as we will see in due course.

These can be reviewed more extensively from [Numpy.org](https://numpy.org/doc/stable/reference/random/generator.html)

In [6]:
rng = np.random.default_rng()

We use the code in the text box above,  in order to best set ourselves up to test the code to follow. Whereby hte rng on the left hand side, stands for random number generator

#### Integers 

Integers as a data type, being used within the numpy.random package. The same as a lot of other functions, the integer subsection of the random funcoint, is dependent on an understanding of its' parameters. i.e, what information we will place into the funciton in order to generate an output. 

In [7]:
rng.integers(0, 10, size=4)

array([3, 0, 7, 5], dtype=int64)

In the code above, we can see that there are three parameters, that have been passed into the funciton.
Firstly, we have 'low' integer, this is the lowest starting point for what will be generated in the output. In this case it is 0. Next, we have the 'high' integer, which is exclusive. This means that the random numbers generated will not take, in this instance, 10, into the output. Lastly, we have the third parameter, Size. Size, in this context, relates to the number of random numbers to be generated in the ouput.

For further examples of this case, please review the [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers) site.

#### Random

As true as it was for Integers, we're dependent upon the parameters, in order to extract the return from the Random Subsection. In this instance, the random funciton will allow for floating points to be taken into consideration. Floating points can be reviewed via clicking ont he following link, should you require more informaiton on them, via [TechTerms](https://techterms.com/definition/floatingpoint#:~:text=As%20the%20name%20implies%2C%20floating,decimal%20places%20are%20called%20integers.). 

For further examples of this case, please review the [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random)

In [8]:
type(rng.random())

float

In [9]:
3 * rng.random((5,)) 

array([2.68475547, 2.36744096, 2.8143733 , 0.41674727, 1.72695831])

#### Choice

Choice has been created with the understanding of creating a single item, or an array for an output. What differentiates it from previosu iterations ofthe package, is that we can code into the parameter an array, for its consideration. The package, however, will not taek in an integer of negative value.  

For more information on the Choice subsection , please review the following link from [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice)

In [10]:
rng.choice(9, (2,5))

array([[6, 7, 4, 1, 1],
       [0, 7, 2, 4, 5]], dtype=int64)

In the example listed above, we have our integer value inserted in the code, in this it is 1. Within the second paramter, we have a list, of type int. This list will form the structure of the output. Working with the brackets, we have the number of arrays that will be generated, 2, in this case, as well as the number of number of numbers that will be randomly chosen within these arrays.

We have also mentioned that we can take into the function, a string. If we create a list of data type string, as follows:

In [11]:
Cars_Manu = ['Audi', 'Seat', 'VW']

In [12]:
rng.choice(Cars_Manu, 5)

array(['VW', 'Audi', 'Audi', 'Seat', 'Seat'], dtype='<U4')

We can see from the array created above that there are multiple instances of the one manufactures name, as the size of the array exceeds the parameters in the variable Cars_Manu.

#### Bytes

The last of the four subsections within the Simple Data funciton, bytes, is used to return just that, bytes. 
The parameter for this snippet of code is limited to one, and that is length of type integer. 

For more information on this subsection, please review the link via [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.bytes.html#numpy.random.Generator.bytes)


In [13]:
rng.bytes(7)

b'\x89q\xf1\x85\xf57\xec'

This is string of length 7, as hard coded into the line.

### Permutations

Within this segement of the package, we are going to be reviewing teo types of order that we can put an array through. 
They are:
- Shuffle
- Permutations

To permute, simply means to change the order of something, as per [Merriam Webster](https://www.merriam-webster.com/dictionary/permutate#:~:text=%3A%20change%2C%20interchange%20especially%20%3A%20to%20arrange%20in%20a%20different%20order)

#### Shuffle

In order to shuffle a list of integers, we must set up our code to accept the integer, as follow.

For more information on this, please review [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html#numpy.random.shuffle)

For further reading on the reshape function, please visit [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle).

In [14]:
Shuf = np.arange(20)

In [15]:
np.random.shuffle(Shuf)

In [16]:
Shuf

array([12,  5, 14, 17,  3, 15, 18, 16, 13, 11,  9,  7,  6,  1, 19,  0,  2,
        8,  4, 10])

We can see from the array that has been returned from the codeblock, that there are 20 integers in the array. You will also see that there is no number 20 in this list, as the list has commenced from the number 0.

In [17]:
Shuf = np.arange(15).reshape((5, 3))
np.random.shuffle(Shuf)
Shuf

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [12, 13, 14],
       [ 9, 10, 11]])

We can also add in the reshape funciton, so that we can create multiple arrays, based on the common denominators that comprise an integer. In the exmaple displayed above, we ahve shuffled through the 15 numbers and divided them into 5 seperate arrays, of 3 numbers each. This is only possible as 5 multiplied by 3 is equal to the number set out in the parameter.

#### Permutations

Similar in its basis to shuffle, the permutations function will accept a integer as well as an array as a parameter. 

For more inforamtion on this topic, please review [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation)

In [18]:
# If we take the basis for our analysis as: 
rng = np.random.default_rng()

In [19]:
# and we try to run through a permutation of an integer, 7. 
rng.permutation(7) 

array([4, 1, 5, 3, 2, 0, 6])

In [20]:
# we can also perform the permutation on an array [1, 2, 3, 4, 5, 6, 7]

In [21]:
rng.permutation([1, 2, 3, 4, 5, 6, 7])

array([6, 5, 7, 3, 4, 2, 1])

### Distributions

The objective of this exercise is to review at elast five different types of distribution.

The five types of distribution that we are going to review are: 

- Binomial
- Chi-Square
- Standard T
- Normal (Gaussian) Distribution
- Zipf


#### Binomial Distribution Overview

For more information [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.binomial.html#numpy.random.Generator.binomial)

Binomial distributuion refers to an event where there are two outcomes from the event. The most common example of a binomial distribtion is the toss of a coin. We can set up our analysis as follows:

In [22]:
# number of trials
n = 10

In [23]:
# Probability of event occuring
p = 0.5

In [24]:
result = rng.binomial(n, p, 100)

In [25]:
result

array([5, 6, 4, 5, 6, 7, 1, 2, 7, 4, 2, 7, 7, 7, 4, 4, 3, 4, 3, 5, 5, 4,
       3, 5, 4, 5, 7, 5, 4, 3, 4, 4, 2, 5, 3, 3, 6, 6, 7, 5, 6, 6, 6, 2,
       3, 3, 5, 4, 4, 7, 7, 6, 5, 6, 8, 6, 4, 6, 4, 3, 5, 5, 6, 5, 6, 3,
       7, 5, 6, 6, 7, 4, 5, 1, 5, 9, 4, 7, 6, 6, 6, 6, 3, 5, 3, 5, 6, 4,
       8, 5, 5, 4, 6, 4, 5, 7, 7, 5, 7, 8], dtype=int64)

In [26]:
# we can see fromt eh paramter above the number 100. This represents the number of times the trial occured. 
# That is, there were 10 tosses of a coin completed 100 times.

##### Plotting the data

#### Chi-Square Distribution Overview

This distribution test has been created in order to test teh degrees of freedom. Thse degrees of freedom are measured via the sum of squared standard deviates of the distribution. 

For more information on this, please review [OnlineStatbook](http://onlinestatbook.com/2/chi_square/distribution.html). The code in the block below was retrieved from: [numpy.Org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.chisquare.html#numpy.random.Generator.chisquare)

In [27]:
rng.chisquare(12,4)

array([12.11303101,  7.197684  ,  8.81502049,  7.04557999])

##### Plotting the data

##### Standard T 

Th Standard T sitribution devlops on in some ways from Ch-Square, in that it encompasses degrees of freedom. 
The T-Distribution, also refered to as the Student's T Distribution according to [Stat Trek](https://stattrek.com/probability-distributions/t-distribution.aspx). This distrubtiuon is briguht in when the sample isn't as large as would be expceted, whilst the variance is also unkonwn. 

Side Note: "The derivation of the t-distribution was first published in 1908 by William Gosset while working for the Guinness Brewery in Dublin. Due to proprietary issues, he had to publish under a pseudonym, and so he used the name Student." as retrieved from [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_t.html#numpy.random.Generator.standard_t) 

The t Score information can be retrieved from teh site [Numpy](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_t.html#numpy.random.Generator.standard_t)

In [28]:
Collection = np.array([123, 456, 789, 987, 654, 321])

In [29]:
s = rng.standard_t(10, size=100000)

# where 10 is the degrees of freedom

In [30]:
np.mean(Collection)

555.0

In [31]:
Collection.std(ddof=1)

316.9738159533055

In [32]:
t = (np.mean(Collection)-7725)/(Collection.std(ddof=1)/np.sqrt(len(Collection)))

#### Plotting The data

#### Normal (Gaussian) Distrubtion

The normal distrubtion is enacted when there is a need to observe a large array of information across a spectrum. These, when placed in a plot, are observed as a bell curve distribution. Such is ht eimportanc eof this bell curve distrubtion, to be viewed, we nbeed to ensure that we have access to the centre of the curve. i.e. Create a Mean and Standard Deviation.

For more information on the normal distrubtion [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal)

In [33]:
a = 0

# this can be our mean

In [34]:
b = 0.2

# this can be our standard deviation


In [35]:
# Therefore

c = rng.normal(a, b, 100)

In [36]:
# Validate mean and the variance 

abs(a - np.mean(c))

0.006904212554379508

In [37]:
abs(c - np.std(c, ddof = 1))

array([0.41054707, 0.1170444 , 0.0619647 , 0.09132501, 0.2088669 ,
       0.1040946 , 0.08759826, 0.02425887, 0.11330285, 0.35169329,
       0.10736284, 0.16101168, 0.24366516, 0.41035284, 0.1620969 ,
       0.24112407, 0.33131623, 0.0918325 , 0.56489085, 0.48951034,
       0.14474729, 0.07438546, 0.2365085 , 0.17382874, 0.19552291,
       0.17174593, 0.0923226 , 0.03129733, 0.20026734, 0.1074559 ,
       0.13944244, 0.30119059, 0.06851257, 0.07698248, 0.16507443,
       0.25146931, 0.34655072, 0.37275428, 0.02409876, 0.43489368,
       0.0844137 , 0.11635055, 0.32721221, 0.1660896 , 0.19618118,
       0.08737402, 0.21922425, 0.26383427, 0.33253391, 0.13392166,
       0.38798699, 0.1783204 , 0.38260604, 0.18179808, 0.01897832,
       0.29511022, 0.11742425, 0.48513908, 0.34152294, 0.00217099,
       0.14013038, 0.51608928, 0.29101539, 0.12455703, 0.25206936,
       0.02938055, 0.15691544, 0.08878188, 0.38098195, 0.04641673,
       0.02453219, 0.1191827 , 0.40386278, 0.34695424, 0.09333

#### Plotting the data

#### Zipf Distribution

The Zipf distribtion is based around the principles of Zipf's Law, whereby the law states that: The Frequebcy of an item is inversely proportional to its rank  in a frequency table. 

For more information on the Zipf Distribution, please review [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.zipf.html#numpy.random.Generator.zipf)

In [38]:
d = 4

In [39]:
Zipf = rng.zipf(a, 1000)

ValueError: a <= 1 or a is NaN

#### Plotting the data     

## Use of Seeds in generating pseudorandom numbers 

Developing on from the information detailed out the outside in BitGenerator Section XX, we have the concept of seeding. 
In order to fully understadn the use of seeds in pseudorandom numbers, we must understand this concept first.

As we have seen in the bitgenerator overview in section XX, there are a number of processes that the bitgenerator is reliant on in order for generators to in-turn allow for methods to be called for random number generation.  

With specifc relation to the use of seeds however, there is another level of detail that we must acknowledge.

### Reference Material 
<br>

Official Numpy site, November 2020

https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random
<br>
Markdown Style Guide, November 2020

https://www.markdownguide.org/basic-syntax/
<br>
Binomial Distribution 

https://www.datacamp.com/community/tutorials/probability-distributions-python
<br>
Explanantion of Tuple 

https://www.programiz.com/python-programming/tuple
<br>
Explanation of Chi-Square Rule

http://onlinestatbook.com/2/chi_square/distribution.html
<br>

Explanation of Students T Distribution

https://stattrek.com/probability-distributions/t-distribution.aspx
<br>

Explamnation of where PCG64 originates
https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html
<br>


 