## Programming for Data Analysis

The purpose of this dicument is to perform a high level analysis of the Numpy.Random package. 



There will be multiple components tot his analysis. The headsings for this analysis, will be as follows. 

- Explain the overall purpose of the package
- Explain the use of the simple random data function. 
- Explain the use of Permutations Funcitons. 
- Expain the use and purpose of at least five distributions functions. 
- Explain the use of seeds in generations pseudorandom numbers.


### Numpy.Random

At it's highest hierarchail structure, the numpy package is divided into two core parts, BitGenerators and Generators. 
We will be at first reviewing the Bitgenerator, via some sample code to demonstrate the packages capabilities.<br>
<br>
The principle purpose of the package is random number generation, as per [Numpy.org](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#quick-start)

### BitGenerator

As per the official documentation on the [numpy.org](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.html#numpy.random.BitGenerator) the bit generator performs a very limited number of tasks within the numpy.random pakage.



In [77]:
import numpy as np

In [78]:
np.random.BitGenerator

numpy.random.bit_generator.BitGenerator

In [79]:
np.random.BitGenerator.random_raw()

TypeError: descriptor 'random_raw' of 'numpy.random.bit_generator.BitGenerator' object needs an argument

This is the source for a bitgenerator test.
Source [numpy.org](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.random_raw.html#numpy.random.BitGenerator.random_raw) 

In [80]:
from numpy.random import default_rng

In [81]:
rg = default_rng(12)
rg.random()

0.2508244581084461

### Generator



Following on from the bitgenerator, we have the generator, which is actually a container for the Bitgenerator

THERE NEEDS TO BE A BUG AUL SPEECH IN HERE ON THE RANDOM.DEFAULT.RNG()

### Simple Random Data

There are four core sections to this section of the package. They are:  

- Integers
- Random
- Choice
- Bytes

These can be reviewed more extensively from [Numpy.org](https://numpy.org/doc/stable/reference/random/generator.html)

In [82]:
rng = np.random.default_rng()

We use the code in the text box above,  in order to best set ourselves up to test the code to follow. Whereby hte rng on the left hand side, stands for random number generator

#### Integers 

Integers as a data type, being used within the numpy.random package. The same as a lot of other functions, the integer subsection of the random funcoint, is dependent on an understanding of its' parameters. i.e, what information we will place into the funciton in order to generate an output. 

In [83]:
rng.integers(0, 10, size=4)

array([5, 2, 9, 4], dtype=int64)

In the code above, we can see that there are three parameters, that have been passed into the funciton.
Firstly, we have 'low' integer, this is the lowest starting point for what will be generated in the output. In this case it is 0. Next, we have the 'high' integer, which is exclusive. This means that the random numbers generated will not take, in this instance, 10, into the output. Lastly, we have the third parameter, Size. Size, in this context, relates to the number of random numbers to be generated in the ouput.

For further examples of this case, please review the [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers) site.

#### Random

As true as it was for Integers, we're dependent upon the parameters, in order to extract the return from the Random Subsection. In this instance, the random funciton will allow for floating points to be taken into consideration. Floating points can be reviewed via clicking ont he following link, should you require more informaiton on them, via [TechTerms](https://techterms.com/definition/floatingpoint#:~:text=As%20the%20name%20implies%2C%20floating,decimal%20places%20are%20called%20integers.). 

For further examples of this case, please review the [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random)

In [84]:
type(rng.random())

float

In [85]:
3 * rng.random((5,)) 

array([1.47772179, 2.4396616 , 0.16377078, 1.11955184, 1.39929515])

#### Choice

Choice has been created with the understanding of creating a single item, or an array for an output. What differentiates it from previosu iterations ofthe package, is that we can code into the parameter an array, for its consideration. The package, however, will not taek in an integer of negative value.  

For more information on the Choice subsection , please review the following link from [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice)

In [86]:
rng.choice(9, (2,5))

array([[5, 7, 4, 0, 2],
       [6, 7, 4, 0, 3]], dtype=int64)

In the example listed above, we have our integer value inserted in the code, in this it is 1. Within the second paramter, we have a list, of type int. This list will form the structure of the output. Working with the brackets, we have the number of arrays that will be generated, 2, in this case, as well as the number of number of numbers that will be randomly chosen within these arrays.

We have also mentioned that we can take into the function, a string. If we create a list of data type string, as follows:

In [87]:
Cars_Manu = ['Audi', 'Seat', 'VW']

In [88]:
rng.choice(Cars_Manu, 5)

array(['VW', 'Audi', 'Seat', 'Audi', 'Seat'], dtype='<U4')

We can see from the array created above that there are multiple instances of the one manufactures name, as the size of the array exceeds the parameters in the variable Cars_Manu.

#### Bytes

The last of the four subsections within the Simple Data funciton, bytes, is used to return just that, bytes. 
The parameter for this snippet of code is limited to one, and that is length of type integer. 

For more information on this subsection, please review the link via [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.bytes.html#numpy.random.Generator.bytes)


In [89]:
rng.bytes(7)

b'4\xe171\x1d\xb4\xba'

This is string of length 7, as hard coded into the line.

### Permutations

Within this segement of the package, we are going to be reviewing teo types of order that we can put an array through. 
They are:
- Shuffle
- Permutations

To permute, simply means to change the order of something, as per [Merriam Webster](https://www.merriam-webster.com/dictionary/permutate#:~:text=%3A%20change%2C%20interchange%20especially%20%3A%20to%20arrange%20in%20a%20different%20order)

#### Shuffle

In order to shuffle a list of integers, we must set up our code to accept the integer, as follow.

For more information on this, please review [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html#numpy.random.shuffle)

For further reading on the reshape function, please visit [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle).

In [90]:
Shuf = np.arange(20)

In [91]:
np.random.shuffle(Shuf)

In [92]:
Shuf

array([ 9, 11, 14,  6,  2, 18,  3, 19,  7,  0, 15, 16,  4, 12,  5,  8, 13,
       10,  1, 17])

We can see from the array that has been returned from the codeblock, that there are 20 integers in the array. You will also see that there is no number 20 in this list, as the list has commenced from the number 0.

In [93]:
Shuf = np.arange(15).reshape((5, 3))
np.random.shuffle(Shuf)
Shuf

array([[12, 13, 14],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

We can also add in the reshape funciton, so that we can create multiple arrays, based on the common denominators that comprise an integer. In the exmaple displayed above, we ahve shuffled through the 15 numbers and divided them into 5 seperate arrays, of 3 numbers each. This is only possible as 5 multiplied by 3 is equal to the number set out in the parameter.

#### Permutations

Similar in its basis to shuffle, the permutations function will accept a integer as well as an array as a parameter. 

For more inforamtion on this topic, please review [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation)

In [94]:
# If we take the basis for our analysis as: 
rng = np.random.default_rng()

In [95]:
# and we try to run through a permutation of an integer, 7. 
rng.permutation(7) 

array([1, 4, 5, 3, 6, 0, 2])

In [96]:
# we can also perform the permutation on an array [1, 2, 3, 4, 5, 6, 7]

In [97]:
rng.permutation([1, 2, 3, 4, 5, 6, 7])

array([7, 1, 5, 3, 2, 6, 4])

### Distributions

The objective of this exercise is to review at elast five different types of distribution.

The five types of distribution that we are going to review are: 

- Binomial
- Chi-Square
- Standard T
- Normal (Gaussian) Distribution
- Zipf


#### Binomial Distribution Overview

For more information [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.binomial.html#numpy.random.Generator.binomial)

Binomial distributuion refers to an event where there are two outcomes from the event. The most common example of a binomial distribtion is the toss of a coin. We can set up our analysis as follows:

In [98]:
# number of trials
n = 10

In [99]:
# Probability of event occuring
p = 0.5

In [100]:
result = rng.binomial(n, p, 100)

In [101]:
result

array([3, 8, 6, 6, 4, 6, 4, 4, 3, 3, 3, 8, 8, 6, 6, 4, 8, 5, 5, 3, 4, 4,
       4, 7, 8, 6, 7, 2, 4, 6, 6, 3, 8, 6, 5, 5, 3, 4, 7, 4, 6, 6, 4, 4,
       3, 6, 5, 4, 5, 4, 4, 1, 3, 4, 4, 3, 3, 6, 5, 8, 7, 4, 6, 6, 6, 5,
       3, 3, 2, 4, 5, 7, 3, 5, 7, 4, 4, 4, 6, 2, 3, 6, 5, 4, 4, 6, 8, 8,
       8, 4, 5, 8, 4, 7, 6, 6, 4, 2, 2, 5], dtype=int64)

In [102]:
# we can see fromt eh paramter above the number 100. This represents the number of times the trial occured. 
# That is, there were 10 tosses of a coin completed 100 times.

##### Plotting the data

#### Chi-Square Distribution Overview

This distribution test has been created in order to test teh degrees of freedom. Thse degrees of freedom are measured via the sum of squared standard deviates of the distribution. 

For more information on this, please review [OnlineStatbook](http://onlinestatbook.com/2/chi_square/distribution.html). The code in the block below was retrieved from: [numpy.Org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.chisquare.html#numpy.random.Generator.chisquare)

In [103]:
rng.chisquare(12,4)

array([10.34075778, 13.75768415, 10.23697555, 11.9743307 ])

##### Plotting the data

##### Standard T 

Th Standard T sitribution devlops on in some ways from Ch-Square, in that it encompasses degrees of freedom. 
The T-Distribution, also refered to as the Student's T Distribution according to [Stat Trek](https://stattrek.com/probability-distributions/t-distribution.aspx). This distrubtiuon is briguht in when the sample isn't as large as would be expceted, whilst the variance is also unkonwn. 

Side Note: "The derivation of the t-distribution was first published in 1908 by William Gosset while working for the Guinness Brewery in Dublin. Due to proprietary issues, he had to publish under a pseudonym, and so he used the name Student." as retrieved from [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_t.html#numpy.random.Generator.standard_t) 

The t Score information can be retrieved from teh site [Numpy](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_t.html#numpy.random.Generator.standard_t)

In [104]:
Collection = np.array([123, 456, 789, 987, 654, 321])

In [105]:
s = rng.standard_t(10, size=100000)

# where 10 is the degrees of freedom

In [106]:
np.mean(Collection)

555.0

In [107]:
Collection.std(ddof=1)

316.9738159533055

In [108]:
t = (np.mean(Collection)-7725)/(Collection.std(ddof=1)/np.sqrt(len(Collection)))

#### Plotting The data

#### Normal (Gaussian) Distrubtion

The normal distrubtion is enacted when there is a need to observe a large array of information across a spectrum. These, when placed in a plot, are observed as a bell curve distribution. Such is ht eimportanc eof this bell curve distrubtion, to be viewed, we nbeed to ensure that we have access to the centre of the curve. i.e. Create a Mean and Standard Deviation.

For more information on the normal distrubtion [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal)

In [109]:
a = 0

# this can be our mean

In [110]:
b = 0.2

# this can be our standard deviation


In [111]:
# Therefore

c = rng.normal(a, b, 100)

In [112]:
# Validate mean and the variance 

abs(a - np.mean(c))

0.008439651023392735

In [113]:
abs(c - np.std(c, ddof = 1))

array([0.04023868, 0.03661337, 0.26587092, 0.09145312, 0.23980082,
       0.34061311, 0.15150681, 0.299514  , 0.46373765, 0.39215186,
       0.33860824, 0.37152274, 0.01104368, 0.12532113, 0.04196039,
       0.26278249, 0.02812756, 0.19259017, 0.25271233, 0.34220633,
       0.15792259, 0.26826898, 0.0618297 , 0.19302495, 0.21563857,
       0.49150818, 0.29801981, 0.44873965, 0.34392456, 0.20338201,
       0.22905616, 0.19982828, 0.30897241, 0.16301152, 0.01887219,
       0.2056633 , 0.15673507, 0.13570042, 0.06511525, 0.19746168,
       0.00220825, 0.34939948, 0.28688605, 0.38859421, 0.28987075,
       0.51099678, 0.44489428, 0.12702291, 0.38102862, 0.05342206,
       0.1754637 , 0.49199576, 0.22821534, 0.14075509, 0.19103776,
       0.09720338, 0.1486317 , 0.38347047, 0.41048776, 0.45725755,
       0.48255964, 0.23847119, 0.00687535, 0.46113921, 0.32477616,
       0.32782978, 0.42312634, 0.21386775, 0.16837085, 0.47082255,
       0.2303016 , 0.03134261, 0.78890669, 0.0305087 , 0.10365

#### Plotting the data

#### Zipf Distribution

The Zipf distribtion is based around the principles of Zipf's Law, whereby the law states that: The Frequebcy of an item is inversely proportional to its rank  in a frequency table. 

For more information on the Zipf Distribution, please review [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.zipf.html#numpy.random.Generator.zipf)

In [114]:
d = 4

In [115]:
Zipf = rng.zipf(a, 1000)

ValueError: a <= 1 or a is NaN

#### Plotting the data     

## Use of Seeds in generating pseudorandom numbers 

### Reference Material 
<br>

Official Numpy site, November 2020

https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random
<br>
Markdown Style Guide, November 2020

https://www.markdownguide.org/basic-syntax/
<br>
Binomial Distribution 

https://www.datacamp.com/community/tutorials/probability-distributions-python
<br>
Explanantion of Tuple 

https://www.programiz.com/python-programming/tuple
<br>
Explanation of Chi-Square Rule

http://onlinestatbook.com/2/chi_square/distribution.html
<br>

Explanation of Students T Distribution

https://stattrek.com/probability-distributions/t-distribution.aspx
<br>


 