## Programming for Data Analysis

The purpose of this dicument is to perform a high level analysis of the Numpy.Random package. 



There will be multiple components tot his analysis. The headsings for this analysis, will be as follows. 

- Explain the overall purpose of the package
- Explain the use of the simple random data function. 
- Explain the use of Permutations Funcitons. 
- Expain the use and purpose of at least five distributions functions. 
- Explain the use of seeds in generations pseudorandom numbers.


### Numpy.Random

At it's highest hierarchail structure, the numpy package is divided into two core parts, BitGenerators and Generators. 
We will be at first reviewing the Bitgenerator, via some sample code to demonstrate the packages capabilities.<br>
<br>
The principle purpose of the package is random number generation, as per [Numpy.org](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#quick-start)

### BitGenerator

As per the official documentation on the [numpy.org](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.html#numpy.random.BitGenerator) the bit generator performs a very limited number of tasks within the numpy.random pakage.



In [4]:
import numpy as np

In [5]:
np.random.BitGenerator

numpy.random.bit_generator.BitGenerator

In [6]:
np.random.BitGenerator.random_raw()

TypeError: descriptor 'random_raw' of 'numpy.random.bit_generator.BitGenerator' object needs an argument

This is the source for a bitgenerator test.
Source [numpy.org](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.random_raw.html#numpy.random.BitGenerator.random_raw) 

In [7]:
from numpy.random import default_rng

In [8]:
rg = default_rng(12)
rg.random()

0.2508244581084461

### Generator



Following on from the bitgenerator, we have the generator, which is actually a container for the Bitgenerator

### Simple Random Data

There are four core sections to this section of the package. They are:  

- Integers
- Random
- Choice
- Bytes

These can be reviewed more extensively from [Numpy.org](https://numpy.org/doc/stable/reference/random/generator.html)

In [9]:
rng = np.random.default_rng()

We use the code in the text box above,  in order to best set ourselves up to test the code to follow. Whereby hte rng on the left hand side, stands for random number generator

#### Integers 

Integers as a data type, being used within the numpy.random package. The same as a lot of other functions, the integer subsection of the random funcoint, is dependent on an understanding of its' parameters. i.e, what information we will place into the funciton in order to generate an output. 

In [21]:
rng.integers(0, 10, size=4)

array([8, 2, 5, 0], dtype=int64)

In the code above, we can see that there are three parameters, that have been passed into the funciton.
Firstly, we have 'low' integer, this is the lowest starting point for what will be generated in the output. In this case it is 0. Next, we have the 'high' integer, which is exclusive. This means that the random numbers generated will not take, in this instance, 10, into the output. Lastly, we have the third parameter, Size. Size, in this context, relates to the number of random numbers to be generated in the ouput.

For further examples of this case, please review the [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers) site.

#### Random

As true as it was for Integers, we're dependent upon the parameters, in order to extract the return from the Random Subsection. In this instance, the random funciton will allow for floating points to be taken into consideration. Floating points can be reviewed via clicking ont he following link, should you require more informaiton on them, via [TechTerms](https://techterms.com/definition/floatingpoint#:~:text=As%20the%20name%20implies%2C%20floating,decimal%20places%20are%20called%20integers.). 

For further examples of this case, please review the [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random)

In [22]:
type(rng.random())

float

In [24]:
3 * rng.random((5,)) 

array([1.34916119, 0.37957297, 2.92635172, 0.45226831, 2.19670441])

#### Choice

Choice has been created with the understanding of creating a single item, or an array for an output. What differentiates it from previosu iterations ofthe package, is that we can code into the parameter an array, for its consideration. The package, however, will not taek in an integer of negative value.  

For more information on the Choice subsection , please review the following link from [Numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice)

In [30]:
rng.choice(9, (2,5))

array([[3, 0, 1, 4, 7],
       [5, 4, 1, 6, 4]], dtype=int64)

In the example listed above, we have our integer value inserted in the code, in this it is 1. Within the second paramter, we have a list, of type int. This list will form the structure of the output. Working with the brackets, we have the number of arrays that will be generated, 2, in this case, as well as the number of number of numbers that will be randomly chosen within these arrays.

We have also mentioned that we can take into the function, a string. If we create a list of data type string, as follows:

In [31]:
Cars_Manu = ['Audi', 'Seat', 'VW']

In [35]:
rng.choice(Cars_Manu, 5)

array(['Audi', 'Audi', 'VW', 'VW', 'Seat'], dtype='<U4')

We can see from the array created above that there are multiple instances of the one manufactures name, as the size of the array exceeds the parameters in the variable Cars_Manu.

#### Bytes

The last of the four subsections within the Simple Data funciton, bytes, is used to return just that, bytes. 
The parameter for this snippet of code is limited to one, and that is length of type integer. 

For more information on this subsection, please review the link via [numpy.org](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.bytes.html#numpy.random.Generator.bytes)


In [40]:
rng.bytes(7)

b'\xff\xf8\x99\xb9&\x84\x85'

This is string of length 7, as hard coded into the line.

### Reference Material 
Official Numpy site, November 2020

https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#module-numpy.random

Markdown Style Guide, November 2020

https://www.markdownguide.org/basic-syntax/

 